// src/mocks/data.js
import transport from "@/assets/bus.svg"
import pet from "@/assets/cat.svg"
import food from "@/assets/soup.svg"
import beauty from "@/assets/wand-sparkles.svg"
import income from "@/assets/circle-dollar-sign.svg"
import shopping from "@/assets/handbag.svg"
import entertainment from "@/assets/drama.svg"
import health from "@/assets/heart-pulse.svg"
import bills from "@/assets/receipt.svg"
import travel from "@/assets/tickets-plane.svg"

export const categoryDict = {
  1: food,
  2: transport,
  3: pet,
  4: beauty,
  5: income,
  6: shopping,
  7: entertainment,
  8: health,
  9: bills,
  10: travel,
}

/*export const categories = [
  { id: '1', category_name: 'Food', category_icon_key: 'food', category_type: 'expense', icon: food  },
  { id: '2', category_name: 'Transport', category_icon_key: 'transport', category_type: 'expense', icon: transport },
  { id: '3', category_name: 'Pet', category_icon_key: 'pet', category_type: 'expense', icon: pet },
  { id: '4', category_name: 'Beauty', category_icon_key: 'beauty', category_type: 'expense', icon: beauty},
  { id: '5', category_name: 'Income', category_icon_key: 'income', category_type: 'income', icon: income},
  { id: '6', category_name: 'Shopping', category_icon_key: 'shopping', category_type: 'expense', icon: shopping  },
  { id: '7', category_name: 'Entertainment', category_icon_key: 'entertainment', type: 'expense', icon: entertainment },
  { id: '8', category_name: 'Health', category_icon_key: 'health', category_type: 'expense', icon: health },
  { id: '9', category_name: 'Bills', category_icon_key: 'bills', category_type: 'expense', icon: bills},
  { id: '10', category_name: 'Travel', category_icon_key: 'travel', category_type: 'expense', icon: travel},
]*/

/*
create table public.budgets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  amount_cents numeric null,
  start_datetime timestamp with time zone null,
  end_datetime timestamp with time zone null,
  duration text null,
  is_recurring boolean null default false,
  category_id bigint null,
  constraint budgets_pkey primary key (id),
  constraint budgets_category_id_fkey foreign KEY (category_id) references categories (id)
) TABLESPACE pg_default;

create table public.categories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  category_name text null default ''::text,
  category_icon_key text null default ''::text,
  category_type text null default ''::text,
  constraint categories_pkey primary key (id)
) TABLESPACE pg_default;

create table public.transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  category_id bigint null,
  amount_cents numeric null,
  notes text null default ''::text,
  transaction_datetime timestamp with time zone null,
  is_recurring boolean null default false,
  type text null,
  constraint transactions_pkey primary key (id),
  constraint transactions_category_id_fkey foreign KEY (category_id) references categories (id)
) TABLESPACE pg_default;


*/